apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurante-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurantitoservice
  template:
    metadata:
      labels:
        app: restaurantitoservice
    spec:
      containers:
        - name: restaurantitoservice
          image: rusok/restaurante:5.2
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: restaurante-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: restaurantitoservice
  ports:
    - name: restaurantitoservice
      protocol: TCP
      port: 8080
      targetPort: 8080